// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int numcount = Integer.parseInt(args[0]);
		int timeless = 0;
		int timeabove = 0;
		for (int count = 0; count < numcount; count++) {
		double a = Math.random();
		if (a < 0.5){
			timeless++ ;
		} else {
			timeabove++ ;
		}
	}
	System.out.println("> 0.5:   " + timeless + " times");
	System.out.println("<= 0.5:  " + timeabove + " times");
	if (timeless != 0) {
			double ratio = (double) timeabove / timeless;
			System.out.println("Ratio:   " + ratio);
	}
	}
}